Repository SierraSystems/ntt-data-notification-service, pull requests merged in 2020-05, with the labels that each got.

#23 Update namespace
  src/main/java/com/nttdata/splunknotificationservice/SplunkNotificationServiceApplication.java
  src/main/java/com/nttdata/splunknotificationservice/configuration/SplunkProperites.java
  src/main/java/com/nttdata/splunknotificationservice/controller/AlertNotificationController.java
  src/main/java/com/nttdata/splunknotificationservice/rocket/RocketChannelService.java
  src/main/java/com/nttdata/splunknotificationservice/rocket/models/RocketMessage.java
  src/main/java/com/nttdata/splunknotificationservice/service/ChannelService.java
  src/main/java/com/nttdata/splunknotificationservice/service/ChannelServiceFactory.java
  src/main/java/com/nttdata/splunknotificationservice/service/ChatApp.java
  src/main/java/com/nttdata/splunknotificationservice/service/WebHookService.java
  src/main/java/com/nttdata/splunknotificationservice/service/WebHookServiceImpl.java
  src/main/java/com/nttdata/splunknotificationservice/splunk/models/SplunkAlert.java
  src/main/java/com/nttdata/splunknotificationservice/splunk/models/SplunkResult.java
  src/main/java/com/nttdata/splunknotificationservice/splunk/models/SplunkWebHookParams.java
  src/main/java/com/nttdata/splunknotificationservice/splunk/models/SplunkWebHookUrls.java
  src/main/java/com/nttdata/splunknotificationservice/teams/TeamsChannelService.java
  src/main/java/com/nttdata/splunknotificationservice/teams/models/TeamsAction.java
  src/main/java/com/nttdata/splunknotificationservice/teams/models/TeamsCard.java
  src/main/java/com/nttdata/splunknotificationservice/teams/models/TeamsFact.java
  src/main/java/com/nttdata/splunknotificationservice/teams/models/TeamsInput.java
  src/main/java/com/nttdata/splunknotificationservice/teams/models/TeamsMessage.java
  src/main/java/com/nttdata/splunknotificationservice/teams/models/TeamsPotentialActions.java
  src/main/java/com/nttdata/splunknotificationservice/teams/models/TeamsSection.java
  src/main/resources/public/index.html
Labels: breaking, porkchop sandwiches

#24 Application Frontend
  src/main/resources/public/index.html
  src/main/resources/public/index.js
Labels: enhancement

#31 Add/remove urls
  src/main/resources/public/index.html
  src/main/resources/public/index.js
Labels: enhancement

#32 Error checking and validation for inputs
  src/main/resources/public/index.html
  src/main/resources/public/index.js
Labels: enhancement

#81 Add tests and refactoring
  src/test/java/com/nttdata/nttdatanotificationservice/service/ChannelServiceFactoryTest.java
  src/test/java/com/nttdata/nttdatanotificationservice/teams/TeamsChannelServiceTest.java
Labels: porkchop sandwiches

#80 Frontend Refactoring & Fixes
  src/main/resources/public/index.html
  src/main/resources/public/index.js
Labels: enhancement

#92 README!!! No like actually, please read me!
  Dockerfile
  README.md
  src/main/resources/public/testrunner.html
Labels: documentation

#93 PLEASE README!!
  README.md
Labels: documentation

#98 fix integrity shas
  package-lock.json
Labels: bug

#102 Update readme naming
  README.md
Labels: documentation
