Repository SierraSystems/ntt-data-notification-service, pull requests merged in 2020-06, with the labels that each got.

#108 New NTT themed beautiful frontend
  README.md
  src/main/resources/public/img/copy.svg
  src/main/resources/public/img/logo.png
  src/main/resources/public/img/rocketchat.png
  src/main/resources/public/img/teams.png
  src/main/resources/public/index.css
  src/main/resources/public/index.html
  src/main/resources/public/index.js
  src/main/resources/public/testrunner.html
Labels: enhancement, frontend

#103 Update: docker-compose and README
  README.md
  docker-compose.yml
  src/main/resources/application.properties
  src/main/resources/public/index.js
  src/test/java/com/nttdata/nttdatanotificationservice/controller/SplunkNotificationControlllerTest.java
Labels: breaking, porkchop sandwiches

#115 Fix input field UX
  src/main/resources/public/index.js
Labels: bug, enhancement, frontend

#129 Testing adding JS coverage to codeclimate
  .github/workflows/jacoco-coverage.yml
  .gitignore
  package-lock.json
  package.json
  src/main/resources/public/index.js
  src/main/resources/public/index.test.js
Labels: porkchop sandwiches

#130 Update badges
  README.md
Labels: porkchop sandwiches
